name: sliver_table
description: A table widget that can be used inside of a [CustomScrollView].
version: 0.0.1
homepage: https://github.com/omarsahl/sliver_table
author: omarsahl <omarsahl.com>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sliver_tools: ^0.2.5
  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
